name: Smoke Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-order astroquery astropy pyarrow

      - name: Run smoke tests
        env:
          PYTHONPATH: .
        run: |
          python ci/run_all_tests.py 2025-10-17_gaia_ssz_real
